import type { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
    await knex("brands").del();
    await knex("device_types").del();
    await knex("resellers").del();
    await knex("device_statuses").del();
    await knex("devices").del();

    await knex("brands").insert([
        { id: 1, name: "Lenovo" },
        { id: 2, name: "HP" },
        { id: 3, name: "Dell" },
        { id: 4, name: "Apple" },
        { id: 5, name: "Asus" },
        { id: 6, name: "Acer" },
    ]);

    await knex("device_types").insert([
        { id: 1, name: "Smartphone" },
        { id: 2, name: "Tablet" },
        { id: 3, name: "Laptop" },
        { id: 4, name: "PC" },
        { id: 5, name: "Monitor" },
    ]);

    await knex("resellers").insert([
        { id: 1, name: "Amazon" },
        { id: 2, name: "Temu" },
        { id: 3, name: "AliExpress" },
    ]);

    await knex("device_statuses").insert([
        { id: 1, name: "Available" },
        { id: 2, name: "In Use" },
        { id: 3, name: "Reserved" },
        { id: 4, name: "Under Repair" },
        { id: 5, name: "Stolen" },
        { id: 6, name: "Retired" },
    ]);

    await knex("devices").insert([
        {
            id: 1,
            brand_id: 3, // Dell
            device_type_id: 3, // Laptop
            reseller_id: 1,
            device_status_id: 1,
            purchased_at: "2022-03-15",
            model_name: "Dell Latitude 7420",
            serial_number: "SN-DL-001-7420",
            warranty_months: 36,
            lifespan_months: 60,
            price: "1299.99",
        },
        {
            id: 2,
            brand_id: 2, // HP
            device_type_id: 3,
            reseller_id: 1,
            device_status_id: 1,
            purchased_at: "2023-07-10",
            model_name: "HP EliteBook 850 G8",
            serial_number: "SN-HP-002-850G8",
            warranty_months: 24,
            lifespan_months: 60,
            price: "1199.50",
        },
        {
            id: 3,
            brand_id: 4, // Apple
            device_type_id: 1, // Smartphone
            reseller_id: 2,
            device_status_id: 2,
            purchased_at: "2021-11-05",
            model_name: "Apple iPhone 13",
            serial_number: "SN-AP-003-IP13",
            warranty_months: 12,
            lifespan_months: 36,
            price: "899.00",
        },
        {
            id: 4,
            brand_id: 1, // Lenovo
            device_type_id: 4, // PC
            reseller_id: 3,
            device_status_id: 4,
            purchased_at: "2020-06-20",
            model_name: "Lenovo ThinkCentre M720",
            serial_number: "SN-LN-004-M720",
            warranty_months: 36,
            lifespan_months: 72,
            price: "749.99",
        },
        {
            id: 5,
            brand_id: 3,
            device_type_id: 5, // Monitor
            reseller_id: 3,
            device_status_id: 3,
            purchased_at: "2022-01-12",
            model_name: "Dell UltraSharp U2720Q",
            serial_number: "SN-DL-005-U2720Q",
            warranty_months: 24,
            lifespan_months: 60,
            price: "499.99",
        },
        {
            id: 6,
            brand_id: 6, // Acer
            device_type_id: 3,
            reseller_id: 1,
            device_status_id: 1,
            purchased_at: "2018-09-30",
            model_name: "Acer Aspire 5",
            serial_number: "SN-AC-006-A515",
            warranty_months: 24,
            lifespan_months: 48,
            price: "649.00",
        },
        {
            id: 7,
            brand_id: 5, // Asus
            device_type_id: 2, // Tablet
            reseller_id: 1,
            device_status_id: 2,
            purchased_at: "2023-02-18",
            model_name: "Asus ZenPad 10",
            serial_number: "SN-AS-007-ZP10",
            warranty_months: 12,
            lifespan_months: 36,
            price: "399.99",
        },
        {
            id: 8,
            brand_id: 4,
            device_type_id: 1,
            reseller_id: 2,
            device_status_id: 1,
            purchased_at: "2024-01-08",
            model_name: "Apple iPhone 14 Pro",
            serial_number: "SN-AP-008-IP14P",
            warranty_months: 24,
            lifespan_months: 48,
            price: "1299.00",
        },
        {
            id: 9,
            brand_id: 1,
            device_type_id: 3,
            reseller_id: 3,
            device_status_id: 1,
            purchased_at: "2021-04-14",
            model_name: "Lenovo ThinkPad X1 Carbon",
            serial_number: "SN-LN-009-X1C",
            warranty_months: 36,
            lifespan_months: 72,
            price: "1599.99",
        },
        {
            id: 10,
            brand_id: 6,
            device_type_id: 5,
            reseller_id: 1,
            device_status_id: 2,
            purchased_at: "2020-12-11",
            model_name: "Acer Nitro VG271",
            serial_number: "SN-AC-010-VG271",
            warranty_months: 24,
            lifespan_months: 60,
            price: "299.99",
        },
        {
            id: 11,
            brand_id: 5,
            device_type_id: 3,
            reseller_id: 2,
            device_status_id: 1,
            purchased_at: "2022-08-25",
            model_name: "Asus VivoBook 15",
            serial_number: "SN-AS-011-VB15",
            warranty_months: 24,
            lifespan_months: 60,
            price: "899.99",
        },
        {
            id: 12,
            brand_id: 3,
            device_type_id: 4,
            reseller_id: 1,
            device_status_id: 3,
            purchased_at: "2019-05-17",
            model_name: "Dell OptiPlex 7090",
            serial_number: "SN-DL-012-7090",
            warranty_months: 36,
            lifespan_months: 72,
            price: "899.99",
        },
        {
            id: 13,
            brand_id: 4,
            device_type_id: 2,
            reseller_id: 3,
            device_status_id: 1,
            purchased_at: "2023-10-02",
            model_name: "Apple iPad Air",
            serial_number: "SN-AP-013-IPAIR",
            warranty_months: 12,
            lifespan_months: 36,
            price: "699.00",
        },
        {
            id: 14,
            brand_id: 1,
            device_type_id: 2,
            reseller_id: 2,
            device_status_id: 4,
            purchased_at: "2021-09-19",
            model_name: "Lenovo Tab P11",
            serial_number: "SN-LN-014-P11",
            warranty_months: 24,
            lifespan_months: 48,
            price: "349.99",
        },
        {
            id: 15,
            brand_id: 5,
            device_type_id: 3,
            reseller_id: 1,
            device_status_id: 1,
            purchased_at: "2024-02-28",
            model_name: "Asus ROG Zephyrus G14",
            serial_number: "SN-AS-015-G14",
            warranty_months: 24,
            lifespan_months: 60,
            price: "1799.99",
        },
        {
            id: 16,
            brand_id: 2,
            device_type_id: 5,
            reseller_id: 3,
            device_status_id: 2,
            purchased_at: "2022-11-30",
            model_name: "HP E27 G4",
            serial_number: "SN-HP-016-E27G4",
            warranty_months: 12,
            lifespan_months: 48,
            price: "259.99",
        },
        {
            id: 17,
            brand_id: 3,
            device_type_id: 3,
            reseller_id: 2,
            device_status_id: 1,
            purchased_at: "2023-03-12",
            model_name: "Dell XPS 15",
            serial_number: "SN-DL-017-XPS15",
            warranty_months: 12,
            lifespan_months: 36,
            price: "1899.99",
        },
        {
            id: 18,
            brand_id: 4,
            device_type_id: 3,
            reseller_id: 1,
            device_status_id: 3,
            purchased_at: "2020-08-08",
            model_name: "MacBook Pro 16",
            serial_number: "SN-AP-018-MBP16",
            warranty_months: 24,
            lifespan_months: 72,
            price: "2499.00",
        },
        {
            id: 19,
            brand_id: 1,
            device_type_id: 4,
            reseller_id: 2,
            device_status_id: 2,
            purchased_at: "2019-01-21",
            model_name: "Lenovo IdeaCentre 5",
            serial_number: "SN-LN-019-IDC5",
            warranty_months: 24,
            lifespan_months: 60,
            price: "799.99",
        },
        {
            id: 20,
            brand_id: 6,
            device_type_id: 2,
            reseller_id: 3,
            device_status_id: 1,
            purchased_at: "2024-04-05",
            model_name: "Acer Iconia Tab 10",
            serial_number: "SN-AC-020-ICT10",
            warranty_months: 12,
            lifespan_months: 48,
            price: "279.99",
        },
    ]);
};
